/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication20;
import java.awt.AWTException;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.time.Clock;
import java.time.Instant;
import java.util.Scanner;
import java.util.Timer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
/**
 *
 * @author ali
 */
public class WindowsScreen extends javax.swing.JFrame {

    /**
     * Creates new form WindowsScreen
     */
    public WindowsScreen() {
        initComponents();
        //SHOW MY FRAME ON SCREEN!
        this.setVisible(true);
        // TITLE OF YOUR WINDOWS FRAME!
        this.setTitle("Screen Capture/designed By Ali.Akhi");
        //SIZE OF YPOUR WINDOWS FRAME!
        this.setSize(700, 700);
        //SET YOUR WINDOWS FRAME POSITION!
        this.setLocationRelativeTo(null);
        //when i close the windows frime program be stop!
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
    }
    
    public int Timer(){
        var T= Integer.parseInt(TimerInput.getText());
        return T;
    }
    
    public int Counter(){
        var C= Integer.parseInt(NumInput.getText());
        return C;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        NumInput = new javax.swing.JTextField();
        TimerInput = new javax.swing.JTextField();
        ScanBtn = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        JsliderWidth = new javax.swing.JSlider();
        JsliderHeight = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        NumInput.setBackground(new java.awt.Color(255, 102, 204));
        NumInput.setForeground(new java.awt.Color(0, 51, 102));
        NumInput.setText("Number");
        getContentPane().add(NumInput);
        NumInput.setBounds(170, 140, 64, 23);

        TimerInput.setBackground(new java.awt.Color(255, 102, 204));
        TimerInput.setForeground(new java.awt.Color(0, 51, 102));
        TimerInput.setText("Timer");
        getContentPane().add(TimerInput);
        TimerInput.setBounds(80, 140, 49, 23);

        ScanBtn.setBackground(new java.awt.Color(204, 204, 255));
        ScanBtn.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        ScanBtn.setForeground(new java.awt.Color(0, 51, 102));
        ScanBtn.setText("Go");
        ScanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScanBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ScanBtn);
        ScanBtn.setBounds(70, 200, 60, 30);

        jProgressBar1.setStringPainted(true);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(140, 210, 146, 20);

        JsliderWidth.setBackground(new java.awt.Color(255, 255, 255));
        JsliderWidth.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        JsliderWidth.setForeground(new java.awt.Color(102, 102, 255));
        JsliderWidth.setMajorTickSpacing(10);
        JsliderWidth.setMaximum(120);
        JsliderWidth.setPaintTicks(true);
        JsliderWidth.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                JsliderWidthAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        JsliderWidth.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                JsliderWidthStateChanged(evt);
            }
        });
        getContentPane().add(JsliderWidth);
        JsliderWidth.setBounds(20, 50, 360, 40);

        JsliderHeight.setBackground(new java.awt.Color(255, 255, 255));
        JsliderHeight.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        JsliderHeight.setForeground(new java.awt.Color(102, 102, 255));
        JsliderHeight.setMajorTickSpacing(10);
        JsliderHeight.setOrientation(javax.swing.JSlider.VERTICAL);
        JsliderHeight.setPaintTicks(true);
        JsliderHeight.setToolTipText("");
        JsliderHeight.setValue(100);
        getContentPane().add(JsliderHeight);
        JsliderHeight.setBounds(10, 100, 30, 350);

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/ali/Desktop/stay at home.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, -50, 640, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ScanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScanBtnActionPerformed
        try {
            Robot Rob = new Robot();
            Screensh Myobj = new Screensh();
            
            Converter Myconverter= new Converter();
            Clock clock = Clock.systemDefaultZone();
            int w = JsliderWidth.getValue()*10;
            int h = JsliderHeight.getValue()*10;
            int n = Integer.parseInt(NumInput.getText());
            int s = Integer.parseInt(TimerInput.getText());
            Myobj.setWidth(w);
            Myobj.setHeight(h);
            Toolkit T = Toolkit.getDefaultToolkit();
            Timer timer = new Timer();
            timer.schedule(
                    new java.util.TimerTask() {
                        @Override
                        public void run() {
                            for(int i=0; i<=100+1; i=i+100/n)
                                jProgressBar1.setValue(i);
                        }
                    },8000
            );
            for(int i = 0; i< n; i++) {
                try {
                    try {
                        Thread.sleep(s*1000);
                    } catch(InterruptedException ie) {}
                    System.out.println("released");
                    Instant instantObj = clock.instant();
                    String a = instantObj.toString();
                    File input = new File(a+".png");
                    File output = new File(a+".pdf");
                    BufferedImage Img = Rob.createScreenCapture(Myobj.Cpture());
                    try {
                        Myobj.ScreenSht(Img, input);
                    } catch (IOException ex) {
                        Logger.getLogger(WindowsScreen.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    Myconverter.pdfConverter(input, output);
                    
                } catch(Exception ex) {Logger.getLogger(WindowsScreen.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        } catch (AWTException ex) {
            Logger.getLogger(WindowsScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ScanBtnActionPerformed

    private void JsliderWidthAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_JsliderWidthAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_JsliderWidthAncestorAdded

    private void JsliderWidthStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_JsliderWidthStateChanged

    }//GEN-LAST:event_JsliderWidthStateChanged

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider JsliderHeight;
    private javax.swing.JSlider JsliderWidth;
    private javax.swing.JTextField NumInput;
    private javax.swing.JButton ScanBtn;
    private javax.swing.JTextField TimerInput;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
